### ISSUE TITLE
Is it possible to printout float without scientific notation?

### ISSUE THREAD

**Issue by serzhiio** [dtolnay/ryu#14]
subj

**Comment by plokhotnyuk** [comment]
Currently, this repo has no option for that, while there are some versions of the Ryu algorithm which implement such kind of option and set it internally for some range of exponents, usually from -3 to 6 inclusive:
- [original repo](https://github.com/ulfjack/ryu/blob/66ba13274ca0247ad46fd4fe8a2f6d36f5d39b01/src/main/java/info/adams/ryu/RyuDouble.java#L349-L387)
- [jsoniter-scala repo](https://github.com/plokhotnyuk/jsoniter-scala/blob/2920ef7c482ea2486b1b40f2b4949abc19ad1eb7/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1952-L1975)

**Comment by dtolnay** [comment]
Yes, the algorithm is good for this. You would need to plug in your own alternative to [this code](https://github.com/dtolnay/ryu/blob/397923c3f115bdc0372aab23787c6fd66517f6dc/src/pretty/mod.rs#L73-L118) which is what converts from mantissa/exponent to scientific notation.

**Comment by loyd** [comment]
Any chance to have it built in?

**Comment by dtolnay** [comment]
I am not interested in having it built in.
