### ISSUE TITLE
Ryu format 3.2 as 0.0 on powerpc64le

### ISSUE THREAD

**Issue by NobodyXu** [dtolnay/ryu#47]
In my PR https://github.com/ParkMyCar/compact_str/pull/16 , when formatting 3.2 using ryu (currently disabled due to bug), it gives me 0.0 on target powerpc64le instead of 3.2

P.S. formatting using std on the target gives me 0

**Comment by dtolnay** [comment]
If std::fmt is formatting it as 0 as well, I would propose that this is unlikely to be a bug in this crate.

Once whatever is broken in std or rustc has been fixed, if ryu is still incorrect after that, please follow up.

**Comment by NobodyXu** [comment]
Sure.

**Comment by NobodyXu** [comment]
@dtolnay Reopened this as the latest nightly `rustc` has fixed the error formatting `3.2_f32` as `0.0`, but `ryu` still format it as `0.0` according to [this CI log](https://github.com/ParkMyCar/compact_str/runs/6301456468?check_suite_focus=true).

**Comment by dtolnay** [comment]
What was the fix?

**Comment by NobodyXu** [comment]
> What was the fix?

We didn't fix the code, somehow after updating nightly, the bug is fixed, but ryu still format 3.2_f32 as  0.0, but format the f64 correctly.

I also discovered a minor bug in std format, f32::NEG_INFINITY is formatted as "inf" instead of "-inf".

**Comment by dtolnay** [comment]
If it randomly goes away without any relevant code changes in std's formatting code, I am still extremely skeptical that it would need a code change in ryu's formatting code as opposed to the bug being elsewhere.

**Comment by NobodyXu** [comment]
> If it randomly goes away without any relevant code changes in std's formatting code, I am still extremely skeptical that it would need a code change in ryu's formatting code as opposed to the bug being elsewhere.

Yeah, it looks like a bug in generating the assembly in `rustc` or `llvm`.
