### ISSUE TITLE
Make `pretty` mod or `write_to_ryu_buffer` function public?

### ISSUE THREAD

**Issue by Alexhuszagh** [dtolnay/ryu#5]
I already have an intermediate stack buffer, but would like to use the pretty formatting via `pretty:{f2s_buffered_n, d2s_buffered_n}`. Right now, this is publicly exposed via `Float::write_to_ryu_buffer`, however, this is very clearly not a public API and likely to change.

Would you be willing to make any guarantees about the `write_to_ryu_buffer` method in the `Float` trait, either in the current form, or some new form, or expose the `pretty:{f2s_buffered_n, d2s_buffered_n}` functions publicly?

**Comment by dtolnay** [comment]
How's this? #6

**Comment by Alexhuszagh** [comment]
@dtolnay Excellent, thank you!

**Comment by dtolnay** [comment]
Okay. :) I published 0.2.7 with those functions exposed. Thanks!
